# Generated by Django 5.2.1 on 2025-06-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('business_email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('current_locations', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('consent', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
