# Generated by Django 5.1.2 on 2025-03-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCookies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField()),
                ('accepted_cookies', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
