# Generated by Django 5.1.2 on 2025-03-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycookieprivacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercookies',
            name='functional_advertising',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercookies',
            name='functional_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercookies',
            name='functional_personalisation',
            field=models.BooleanField(default=False),
        ),
    ]
