# Generated by Django 5.1.2 on 2025-05-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='feedback_audio/'),
        ),
    ]
