# Generated by Django 5.2.1 on 2026-09-07 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_profile_picture'),
        ('customerpanel', '0004_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPoints',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_points', models.PositiveBigIntegerField(default=0)),
                ('last_daily_claim_date', models.DateField(blank=True, null=True)),
                ('streak_days', models.PositiveSmallIntegerField(default=0)),
                ('day_7_bonus_awarded', models.BooleanField(default=False)),
                ('day_14_bonus_awarded', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('streak_days__gte', 0), ('streak_days__lte', 14)), name='customerpoints_streak_range'), models.CheckConstraint(condition=models.Q(models.Q(('last_daily_claim_date__isnull', True), ('streak_days', 0)), models.Q(('last_daily_claim_date__isnull', False), ('streak_days__gte', 1)), _connector='OR'), name='customerpoints_claim_date'), models.CheckConstraint(condition=models.Q(('day_7_bonus_awarded', False), ('streak_days__gte', 7), _connector='OR'), name='customerpoints_day7_eligible'), models.CheckConstraint(condition=models.Q(('day_14_bonus_awarded', False), ('streak_days', 14), _connector='OR'), name='customerpoints_day14_eligible')],
            },
        ),
    ]
