# Generated by Django 5.2.1 on 2026-09-14 20:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def guard_specs(vendor):
    """Frozen schema guards. They validate new Rewards rows only, never points.

    SQLite equivalents keep the existing isolated browser fixture usable;
    PostgreSQL is the production database and concurrency-test target.
    """
    distinct = 'IS DISTINCT FROM' if vendor == 'postgresql' else 'IS NOT'

    def changed(fields):
        return '(' + ' OR '.join(f'NEW.{field} {distinct} OLD.{field}' for field in fields) + ')'

    snapshot_fields = (
        'id', 'user_id', 'reward_id', 'idempotency_key', 'points_spent',
        'balance_after', 'created_at', 'snapshot_title', 'snapshot_description',
        'snapshot_fulfillment_type', 'snapshot_partner_name', 'snapshot_terms',
        'snapshot_fulfillment_instructions', 'snapshot_information_url',
        'snapshot_country_code', 'snapshot_region', 'snapshot_city',
        'snapshot_location_details', 'snapshot_valid_from', 'snapshot_valid_until',
        'snapshot_benefit_valid_until', 'snapshot_reward_revision',
    )
    return [
        ('cp_redemption_immutable', 'customerpanel_redemption', ['UPDATE'],
         changed(snapshot_fields), 'Redemption snapshots are immutable.'),
        ('cp_redemption_keep', 'customerpanel_redemption', ['DELETE'],
         'TRUE', 'Redemptions must be retained; use a status transition.'),
        ('cp_event_append_only', 'customerpanel_redemptionevent', ['UPDATE', 'DELETE'],
         'TRUE', 'Redemption audit events are append-only.'),
        ('cp_code_keep_assignment', 'customerpanel_rewardcode', ['UPDATE'],
         'OLD.redemption_id IS NOT NULL AND ' + changed((
             'id', 'reward_id', 'payload_kind', 'encrypted_payload', 'encryption_key_id',
             'payload_fingerprint', 'redemption_id', 'assigned_at', 'expires_at', 'created_at',
         )), 'Issued reward code data and allocation are immutable.'),
        ('cp_code_keep_issued', 'customerpanel_rewardcode', ['DELETE'],
         'OLD.redemption_id IS NOT NULL', 'Issued reward codes must be retained.'),
        ('cp_code_reward_match', 'customerpanel_rewardcode', ['INSERT', 'UPDATE'],
         "NEW.redemption_id IS NOT NULL AND NOT EXISTS ("
         "SELECT 1 FROM customerpanel_redemption r WHERE r.id = NEW.redemption_id "
         "AND r.reward_id = NEW.reward_id AND ((r.snapshot_fulfillment_type = 'voucher' "
         "AND NEW.payload_kind = 'code') OR (r.snapshot_fulfillment_type = 'external' "
         "AND NEW.payload_kind = 'claim_link')))",
         'Reward code must match its redemption reward and fulfillment type.'),
        ('cp_code_inventory_type', 'customerpanel_rewardcode', ['INSERT', 'UPDATE'],
         "NEW.redemption_id IS NULL AND NOT EXISTS (SELECT 1 FROM customerpanel_reward r "
         "WHERE r.id = NEW.reward_id AND ((r.fulfillment_type = 'voucher' AND NEW.payload_kind = 'code') "
         "OR (r.fulfillment_type = 'external' AND NEW.payload_kind = 'claim_link')))",
         'Private inventory must belong to a voucher or external reward.'),
        ('cp_fulfillment_type', 'customerpanel_rewardfulfillment', ['INSERT', 'UPDATE'],
         "NOT EXISTS (SELECT 1 FROM customerpanel_redemption r WHERE r.id = NEW.redemption_id "
         "AND r.snapshot_fulfillment_type IN ('physical', 'manual'))",
         'Delivery/manual fulfillment requires a matching redemption type.'),
        ('cp_fulfillment_identity', 'customerpanel_rewardfulfillment', ['UPDATE'],
         changed(('id', 'redemption_id', 'created_at')), 'Fulfillment identity is immutable.'),
        ('cp_request_owner_match', 'customerpanel_rewardrequest', ['INSERT', 'UPDATE'],
         "NEW.redemption_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM customerpanel_redemption r "
         "WHERE r.id = NEW.redemption_id AND r.user_id = NEW.user_id AND r.reward_id = NEW.approved_reward_id)",
         'Request redemption must belong to its customer and approved reward.'),
        ('cp_request_keep_redemption', 'customerpanel_rewardrequest', ['UPDATE'],
         'OLD.redemption_id IS NOT NULL AND ' + changed(('id', 'user_id', 'approved_reward_id', 'redemption_id')),
         'A redeemed request cannot be reassigned.'),
    ]


def install_guards(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor not in ('postgresql', 'sqlite'):
        raise RuntimeError('Rewards integrity guards require PostgreSQL or SQLite.')
    for name, table, events, condition, message in guard_specs(vendor):
        for event in events:
            trigger = schema_editor.quote_name(f'{name}_{event.lower()}')
            quoted_table = schema_editor.quote_name(table)
            if vendor == 'postgresql':
                returned = 'OLD' if event == 'DELETE' else 'NEW'
                schema_editor.execute(
                    f"CREATE FUNCTION {trigger}() RETURNS trigger LANGUAGE plpgsql AS $$ "
                    f"BEGIN IF {condition} THEN RAISE EXCEPTION '{message}' USING ERRCODE = '23514'; "
                    f"END IF; RETURN {returned}; END; $$;"
                )
                schema_editor.execute(
                    f'CREATE TRIGGER {trigger} BEFORE {event} ON {quoted_table} '
                    f'FOR EACH ROW EXECUTE FUNCTION {trigger}();'
                )
            else:
                schema_editor.execute(
                    f"CREATE TRIGGER {trigger} BEFORE {event} ON {quoted_table} "
                    f"FOR EACH ROW WHEN {condition} BEGIN SELECT RAISE(ABORT, '{message}'); END;"
                )


def remove_guards(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    for name, table, events, _, _ in reversed(guard_specs(vendor)):
        for event in events:
            trigger = schema_editor.quote_name(f'{name}_{event.lower()}')
            if vendor == 'postgresql':
                schema_editor.execute(f'DROP TRIGGER IF EXISTS {trigger} ON {schema_editor.quote_name(table)};')
                schema_editor.execute(f'DROP FUNCTION IF EXISTS {trigger}();')
            else:
                schema_editor.execute(f'DROP TRIGGER IF EXISTS {trigger};')


class Migration(migrations.Migration):

    dependencies = [
        ('customerpanel', '0005_customerpoints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=400)),
                ('full_description', models.TextField()),
                ('category', models.CharField(choices=[('beauty', 'Beauty'), ('food-drink', 'Food & Drink'), ('travel', 'Travel'), ('entertainment', 'Entertainment'), ('tech-gaming', 'Tech & Gaming'), ('shopping', 'Shopping'), ('experiences', 'Experiences')], max_length=20)),
                ('image_url', models.URLField(blank=True, max_length=2048, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('points_required', models.PositiveBigIntegerField()),
                ('fulfillment_type', models.CharField(choices=[('voucher', 'Voucher/code'), ('external', 'Partner claim link'), ('physical', 'Physical product'), ('manual', 'Manual fulfillment')], max_length=12)),
                ('partner_name', models.CharField(blank=True, max_length=200)),
                ('information_url', models.URLField(blank=True, max_length=2048, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('country_code', models.CharField(blank=True, max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$')])),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('location_details', models.CharField(blank=True, max_length=300)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('benefit_valid_until', models.DateTimeField(blank=True, null=True)),
                ('terms', models.TextField()),
                ('fulfillment_instructions', models.TextField(blank=True)),
                ('stock_remaining', models.PositiveIntegerField(blank=True, help_text='Physical/manual inventory only. Blank means unlimited; zero means unavailable.', null=True)),
                ('max_redemptions_per_customer', models.PositiveIntegerField(blank=True, default=1, help_text='Blank means repeatable without a per-customer limit. Enforced by the future locked redemption service.', null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_limited_time', models.BooleanField(default=False)),
                ('is_exclusive', models.BooleanField(default=False)),
                ('access_scope', models.CharField(choices=[('all_customers', 'All customers'), ('selected_customers', 'Selected customers')], default='all_customers', max_length=20)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eligible_users', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'role': 'customer'}, related_name='eligible_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField(editable=False)),
                ('points_spent', models.PositiveBigIntegerField(editable=False)),
                ('balance_after', models.PositiveBigIntegerField(editable=False)),
                ('snapshot_title', models.CharField(editable=False, max_length=200)),
                ('snapshot_description', models.TextField(editable=False)),
                ('snapshot_fulfillment_type', models.CharField(choices=[('voucher', 'Voucher/code'), ('external', 'Partner claim link'), ('physical', 'Physical product'), ('manual', 'Manual fulfillment')], editable=False, max_length=12)),
                ('snapshot_partner_name', models.CharField(blank=True, editable=False, max_length=200)),
                ('snapshot_terms', models.TextField(editable=False)),
                ('snapshot_fulfillment_instructions', models.TextField(blank=True, editable=False)),
                ('snapshot_information_url', models.URLField(blank=True, editable=False, max_length=2048)),
                ('snapshot_country_code', models.CharField(blank=True, editable=False, max_length=2)),
                ('snapshot_region', models.CharField(blank=True, editable=False, max_length=100)),
                ('snapshot_city', models.CharField(blank=True, editable=False, max_length=100)),
                ('snapshot_location_details', models.CharField(blank=True, editable=False, max_length=300)),
                ('snapshot_valid_from', models.DateTimeField(blank=True, editable=False, null=True)),
                ('snapshot_valid_until', models.DateTimeField(blank=True, editable=False, null=True)),
                ('snapshot_benefit_valid_until', models.DateTimeField(blank=True, editable=False, null=True)),
                ('snapshot_reward_revision', models.PositiveIntegerField(editable=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('refunded_points', models.PositiveBigIntegerField(default=0)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='reward_redemptions', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='customerpanel.reward')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RewardCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload_kind', models.CharField(choices=[('code', 'Voucher code'), ('claim_link', 'Private claim link')], editable=False, max_length=12)),
                ('encrypted_payload', models.BinaryField()),
                ('encryption_key_id', models.CharField(editable=False, max_length=64)),
                ('payload_fingerprint', models.CharField(editable=False, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('redemption', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='private_code', to='customerpanel.redemption')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='private_codes', to='customerpanel.reward')),
            ],
        ),
        migrations.CreateModel(
            name='RewardFulfillment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('dispatched', 'Dispatched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=32)),
                ('country_code', models.CharField(blank=True, max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$')])),
                ('request_details', models.TextField(blank=True)),
                ('customer_update', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('tracking_reference', models.CharField(blank=True, max_length=120)),
                ('tracking_url', models.URLField(blank=True, max_length=2048, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processed_reward_fulfillments', to=settings.AUTH_USER_MODEL)),
                ('redemption', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment', to='customerpanel.redemption')),
            ],
        ),
        migrations.CreateModel(
            name='RewardRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('beauty', 'Beauty'), ('food-drink', 'Food & Drink'), ('travel', 'Travel'), ('entertainment', 'Entertainment'), ('tech-gaming', 'Tech & Gaming'), ('shopping', 'Shopping'), ('experiences', 'Experiences')], max_length=20)),
                ('country_code', models.CharField(blank=True, max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$')])),
                ('city', models.CharField(blank=True, max_length=100)),
                ('reference_url', models.URLField(blank=True, max_length=2048, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_review', 'In review'), ('approved', 'Approved'), ('declined', 'Declined'), ('closed', 'Closed')], default='submitted', max_length=12)),
                ('staff_response', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_requests', to='customerpanel.reward')),
                ('redemption', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='original_request', to='customerpanel.redemption')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_reward_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reward_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RedemptionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('redeemed', 'Redeemed'), ('processing', 'Processing'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], editable=False, max_length=12)),
                ('customer_message', models.TextField(blank=True, editable=False)),
                ('internal_note', models.TextField(blank=True, editable=False)),
                ('points_delta', models.BigIntegerField(default=0, editable=False)),
                ('balance_after', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reward_audit_events', to=settings.AUTH_USER_MODEL)),
                ('redemption', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='customerpanel.redemption')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['redemption', 'created_at'], name='redemptionevent_history_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('event_type__in', ['redeemed', 'refunded'])), fields=('redemption', 'event_type'), name='redemptionevent_once_per_charge'), models.CheckConstraint(condition=models.Q(models.Q(('balance_after__isnull', False), ('event_type', 'redeemed'), ('points_delta__lt', 0)), models.Q(('balance_after__isnull', False), ('event_type', 'refunded'), ('points_delta__gt', 0)), models.Q(('event_type__in', ['processing', 'fulfilled', 'cancelled']), ('points_delta', 0)), _connector='OR'), name='redemptionevent_valid_delta')],
            },
        ),
        migrations.AddIndex(
            model_name='reward',
            index=models.Index(fields=['is_active', 'category'], name='reward_catalog_idx'),
        ),
        migrations.AddIndex(
            model_name='reward',
            index=models.Index(fields=['is_active', 'valid_until'], name='reward_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.CheckConstraint(condition=models.Q(('points_required__gt', 0)), name='reward_positive_cost'),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.CheckConstraint(condition=models.Q(('stock_remaining__isnull', True), ('stock_remaining__gte', 0), _connector='OR'), name='reward_nonnegative_stock'),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.CheckConstraint(condition=models.Q(('max_redemptions_per_customer__isnull', True), ('max_redemptions_per_customer__gt', 0), _connector='OR'), name='reward_positive_customer_limit'),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gt', 0)), name='reward_positive_revision'),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.CheckConstraint(condition=models.Q(('valid_from__isnull', True), ('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='reward_valid_date_order'),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.CheckConstraint(condition=models.Q(('benefit_valid_until__isnull', True), ('valid_from__isnull', True), ('benefit_valid_until__gt', models.F('valid_from')), _connector='OR'), name='reward_benefit_after_start'),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.CheckConstraint(condition=models.Q(('benefit_valid_until__isnull', True), ('valid_until__isnull', True), ('benefit_valid_until__gte', models.F('valid_until')), _connector='OR'), name='reward_benefit_after_window'),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['beauty', 'food-drink', 'travel', 'entertainment', 'tech-gaming', 'shopping', 'experiences'])), name='reward_valid_category'),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.CheckConstraint(condition=models.Q(('fulfillment_type__in', ['voucher', 'external', 'physical', 'manual'])), name='reward_valid_type'),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.CheckConstraint(condition=models.Q(('access_scope__in', ['all_customers', 'selected_customers'])), name='reward_valid_access_scope'),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.CheckConstraint(condition=models.Q(('stock_remaining__isnull', True), ('fulfillment_type__in', ['physical', 'manual']), _connector='OR'), name='reward_single_inventory_source'),
        ),
        migrations.AddIndex(
            model_name='redemption',
            index=models.Index(fields=['user', '-created_at'], name='redemption_history_idx'),
        ),
        migrations.AddIndex(
            model_name='redemption',
            index=models.Index(fields=['user', 'reward'], name='redemption_customer_reward_idx'),
        ),
        migrations.AddIndex(
            model_name='redemption',
            index=models.Index(fields=['status', 'created_at'], name='redemption_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='redemption',
            constraint=models.UniqueConstraint(fields=('user', 'idempotency_key'), name='redemption_unique_attempt'),
        ),
        migrations.AddConstraint(
            model_name='redemption',
            constraint=models.CheckConstraint(condition=models.Q(('points_spent__gt', 0)), name='redemption_positive_cost'),
        ),
        migrations.AddConstraint(
            model_name='redemption',
            constraint=models.CheckConstraint(condition=models.Q(('snapshot_reward_revision__gt', 0)), name='redemption_positive_revision'),
        ),
        migrations.AddConstraint(
            model_name='redemption',
            constraint=models.CheckConstraint(condition=models.Q(('snapshot_fulfillment_type__in', ['voucher', 'external', 'physical', 'manual'])), name='redemption_valid_type'),
        ),
        migrations.AddConstraint(
            model_name='redemption',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'processing', 'fulfilled', 'cancelled'])), name='redemption_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='redemption',
            constraint=models.CheckConstraint(condition=models.Q(('snapshot_valid_from__isnull', True), ('snapshot_valid_until__isnull', True), ('snapshot_valid_until__gt', models.F('snapshot_valid_from')), _connector='OR'), name='redemption_valid_date_order'),
        ),
        migrations.AddConstraint(
            model_name='redemption',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('refunded_at__isnull', True), ('refunded_points', 0)), models.Q(('refunded_at__isnull', False), ('refunded_points', models.F('points_spent'))), _connector='OR'), name='redemption_full_refund_pair'),
        ),
        migrations.AddConstraint(
            model_name='redemption',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_at__isnull', True), ('refunded_at__gte', models.F('created_at')), _connector='OR'), name='redemption_refund_date_order'),
        ),
        migrations.AddConstraint(
            model_name='redemption',
            constraint=models.CheckConstraint(condition=models.Q(('completed_at__isnull', True), ('completed_at__gte', models.F('created_at')), _connector='OR'), name='redemption_completed_order'),
        ),
        migrations.AddIndex(
            model_name='rewardcode',
            index=models.Index(condition=models.Q(('is_active', True), ('redemption__isnull', True)), fields=['reward', 'expires_at'], name='rewardcode_available_idx'),
        ),
        migrations.AddConstraint(
            model_name='rewardcode',
            constraint=models.UniqueConstraint(fields=('reward', 'payload_fingerprint'), name='rewardcode_unique_fingerprint'),
        ),
        migrations.AddConstraint(
            model_name='rewardcode',
            constraint=models.CheckConstraint(condition=models.Q(('encrypted_payload', b''), _negated=True), name='rewardcode_payload_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='rewardcode',
            constraint=models.CheckConstraint(condition=models.Q(('encryption_key_id', ''), _negated=True), name='rewardcode_key_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='rewardcode',
            constraint=models.CheckConstraint(condition=models.Q(('payload_fingerprint__regex', '^[0-9a-f]{64}$')), name='rewardcode_fingerprint_format'),
        ),
        migrations.AddConstraint(
            model_name='rewardcode',
            constraint=models.CheckConstraint(condition=models.Q(('payload_kind__in', ['code', 'claim_link'])), name='rewardcode_valid_kind'),
        ),
        migrations.AddConstraint(
            model_name='rewardcode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_at__isnull', True), ('redemption__isnull', True)), models.Q(('assigned_at__isnull', False), ('redemption__isnull', False)), _connector='OR'), name='rewardcode_assignment_pair'),
        ),
        migrations.AddConstraint(
            model_name='rewardcode',
            constraint=models.CheckConstraint(condition=models.Q(('assigned_at__isnull', True), ('assigned_at__gte', models.F('created_at')), _connector='OR'), name='rewardcode_assignment_date'),
        ),
        migrations.AddConstraint(
            model_name='rewardcode',
            constraint=models.CheckConstraint(condition=models.Q(('assigned_at__isnull', True), ('expires_at__isnull', True), ('assigned_at__lt', models.F('expires_at')), _connector='OR'), name='rewardcode_unexpired_assignment'),
        ),
        migrations.AddIndex(
            model_name='rewardfulfillment',
            index=models.Index(fields=['status', 'created_at'], name='fulfillment_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='rewardfulfillment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'processing', 'dispatched', 'completed', 'cancelled'])), name='fulfillment_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='rewardfulfillment',
            constraint=models.CheckConstraint(condition=models.Q(('dispatched_at__isnull', True), ('dispatched_at__gte', models.F('created_at')), _connector='OR'), name='fulfillment_dispatch_order'),
        ),
        migrations.AddConstraint(
            model_name='rewardfulfillment',
            constraint=models.CheckConstraint(condition=models.Q(('completed_at__isnull', True), ('completed_at__gte', models.F('created_at')), _connector='OR'), name='fulfillment_completed_order'),
        ),
        migrations.AddConstraint(
            model_name='rewardfulfillment',
            constraint=models.CheckConstraint(condition=models.Q(('dispatched_at__isnull', True), ('completed_at__isnull', True), ('completed_at__gte', models.F('dispatched_at')), _connector='OR'), name='fulfillment_delivery_order'),
        ),
        migrations.AddIndex(
            model_name='rewardrequest',
            index=models.Index(fields=['user', '-created_at'], name='rewardrequest_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardrequest',
            index=models.Index(fields=['status', 'created_at'], name='rewardrequest_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='rewardrequest',
            constraint=models.CheckConstraint(condition=models.Q(('category', ''), ('category__in', ['beauty', 'food-drink', 'travel', 'entertainment', 'tech-gaming', 'shopping', 'experiences']), _connector='OR'), name='rewardrequest_valid_category'),
        ),
        migrations.AddConstraint(
            model_name='rewardrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['submitted', 'in_review', 'approved', 'declined', 'closed'])), name='rewardrequest_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='rewardrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'approved'), _negated=True), ('approved_reward__isnull', False), _connector='OR'), name='rewardrequest_approved_reward'),
        ),
        migrations.AddConstraint(
            model_name='rewardrequest',
            constraint=models.CheckConstraint(condition=models.Q(('redemption__isnull', True), ('approved_reward__isnull', False), _connector='OR'), name='rewardrequest_redemption_offer'),
        ),
        migrations.AddConstraint(
            model_name='rewardrequest',
            constraint=models.CheckConstraint(condition=models.Q(('reviewed_at__isnull', True), ('reviewed_at__gte', models.F('created_at')), _connector='OR'), name='rewardrequest_review_order'),
        ),
        migrations.RunPython(install_guards, remove_guards),
    ]
