# Generated by Django 5.2.1 on 2026-09-15 10:15

from importlib import import_module

from django.conf import settings
from django.db import migrations, models


def sqlite_remove_guards(apps, schema_editor):
    # SQLite rebuilds tables for constraints. Preserve 0006 guards across those
    # rebuilds for isolated tests; PostgreSQL never removes its existing guards.
    if schema_editor.connection.vendor == 'sqlite':
        import_module(__package__ + '.0006_rewards_database').remove_guards(apps, schema_editor)


def sqlite_restore_guards(apps, schema_editor):
    if schema_editor.connection.vendor == 'sqlite':
        import_module(__package__ + '.0006_rewards_database').install_guards(apps, schema_editor)


def install_stock_guard(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor not in ('postgresql', 'sqlite'):
        raise RuntimeError('Rewards integrity guards require PostgreSQL or SQLite.')
    sqlite_restore_guards(apps, schema_editor)
    distinct = 'IS DISTINCT FROM' if vendor == 'postgresql' else 'IS NOT'
    condition = (
        f'NEW.stock_reserved_quantity {distinct} OLD.stock_reserved_quantity OR '
        f'(OLD.stock_restored_at IS NOT NULL AND NEW.stock_restored_at {distinct} OLD.stock_restored_at)'
    )
    message = 'Recorded stock reservation and restoration are immutable.'
    if vendor == 'postgresql':
        schema_editor.execute(
            'CREATE FUNCTION cp_redemption_stock_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ '
            f"BEGIN IF {condition} THEN RAISE EXCEPTION '{message}' USING ERRCODE = '23514'; "
            'END IF; RETURN NEW; END; $$;'
        )
        schema_editor.execute(
            'CREATE TRIGGER cp_redemption_stock_immutable BEFORE UPDATE ON customerpanel_redemption '
            'FOR EACH ROW EXECUTE FUNCTION cp_redemption_stock_immutable();'
        )
    else:
        schema_editor.execute(
            'CREATE TRIGGER cp_redemption_stock_immutable BEFORE UPDATE ON customerpanel_redemption '
            f"FOR EACH ROW WHEN {condition} BEGIN SELECT RAISE(ABORT, '{message}'); END;"
        )


def remove_stock_guard(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('DROP TRIGGER cp_redemption_stock_immutable ON customerpanel_redemption;')
        schema_editor.execute('DROP FUNCTION cp_redemption_stock_immutable();')
    elif schema_editor.connection.vendor == 'sqlite':
        schema_editor.execute('DROP TRIGGER cp_redemption_stock_immutable;')
        sqlite_remove_guards(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('customerpanel', '0006_rewards_database'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(sqlite_remove_guards, sqlite_restore_guards),
        migrations.AddField(
            model_name='redemption',
            name='stock_reserved_quantity',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='redemption',
            name='stock_restored_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='redemption',
            constraint=models.CheckConstraint(condition=models.Q(('stock_reserved_quantity__in', [0, 1])), name='redemption_single_stock_unit'),
        ),
        migrations.AddConstraint(
            model_name='redemption',
            constraint=models.CheckConstraint(condition=models.Q(('stock_reserved_quantity', 0), ('snapshot_fulfillment_type__in', ['physical', 'manual']), _connector='OR'), name='redemption_stock_type'),
        ),
        migrations.AddConstraint(
            model_name='redemption',
            constraint=models.CheckConstraint(condition=models.Q(('stock_restored_at__isnull', True), models.Q(('refunded_at__isnull', False), ('stock_reserved_quantity', 1), ('stock_restored_at__gte', models.F('refunded_at'))), _connector='OR'), name='redemption_stock_restore_pair'),
        ),
        migrations.RunPython(install_stock_guard, remove_stock_guard),
    ]
