# Generated by Django 5.2.1 on 2026-09-17 15:58

from django.conf import settings
from django.db import migrations, models
from importlib import import_module


def sqlite_remove_guards(apps, schema_editor):
    # SQLite rebuilds Reward for these constraints. PostgreSQL guards remain live.
    if schema_editor.connection.vendor == 'sqlite':
        import_module(__package__ + '.0006_rewards_database').remove_guards(apps, schema_editor)


def sqlite_restore_guards(apps, schema_editor):
    if schema_editor.connection.vendor == 'sqlite':
        import_module(__package__ + '.0006_rewards_database').install_guards(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('customerpanel', '0007_redemption_stock_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(sqlite_remove_guards, sqlite_restore_guards),
        migrations.AddField(
            model_name='reward',
            name='requires_contact_details',
            field=models.BooleanField(default=False, help_text='Manual rewards only; physical rewards always require a name and email.'),
        ),
        migrations.AddField(
            model_name='reward',
            name='requires_phone',
            field=models.BooleanField(default=False, help_text='Requires contact details. Never collected for voucher or external rewards.'),
        ),
        migrations.AddField(
            model_name='reward',
            name='requires_region',
            field=models.BooleanField(default=False, help_text='Only valid for rewards requiring a shipping address.'),
        ),
        migrations.AddField(
            model_name='reward',
            name='requires_shipping_address',
            field=models.BooleanField(default=False, help_text='Manual rewards only; physical rewards always require delivery details.'),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.CheckConstraint(condition=models.Q(('fulfillment_type__in', ['physical', 'manual']), models.Q(('requires_contact_details', False), ('requires_phone', False), ('requires_region', False), ('requires_shipping_address', False)), _connector='OR'), name='reward_delivery_types_only'),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.CheckConstraint(condition=models.Q(('requires_region', False), ('fulfillment_type', 'physical'), ('requires_shipping_address', True), _connector='OR'), name='reward_region_needs_shipping'),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.CheckConstraint(condition=models.Q(('requires_phone', False), ('fulfillment_type', 'physical'), ('requires_contact_details', True), _connector='OR'), name='reward_phone_needs_contact'),
        ),
        migrations.RunPython(sqlite_restore_guards, sqlite_remove_guards),
    ]
