# Generated by Django 5.2.1 on 2026-09-24 02:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def protect_unlocks(apps, schema_editor):
    table = 'customerpanel_customersectionunlock'
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("""
            CREATE FUNCTION cp_section_unlock_permanent() RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN RAISE EXCEPTION 'Section unlock records are permanent.' USING ERRCODE = '23514'; END;
            $$;
        """)
        schema_editor.execute(f'CREATE TRIGGER cp_section_unlock_permanent BEFORE UPDATE OR DELETE ON {table} '
                              'FOR EACH ROW EXECUTE FUNCTION cp_section_unlock_permanent();')
    elif schema_editor.connection.vendor == 'sqlite':
        for event in ('UPDATE', 'DELETE'):
            schema_editor.execute(f"CREATE TRIGGER cp_section_unlock_{event.lower()} BEFORE {event} ON {table} "
                                  "BEGIN SELECT RAISE(ABORT, 'Section unlock records are permanent.'); END;")


def remove_protection(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('DROP TRIGGER cp_section_unlock_permanent ON customerpanel_customersectionunlock;')
        schema_editor.execute('DROP FUNCTION cp_section_unlock_permanent();')
    elif schema_editor.connection.vendor == 'sqlite':
        for event in ('update', 'delete'):
            schema_editor.execute(f'DROP TRIGGER cp_section_unlock_{event};')


class Migration(migrations.Migration):

    dependencies = [
        ('customerpanel', '0008_reward_fulfillment_requirements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSectionUnlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('discounts', 'Discounts'), ('rewards', 'Rewards'), ('offers', 'Offers'), ('news', 'News'), ('weather', 'Weather')], editable=False, max_length=16)),
                ('points_spent', models.PositiveSmallIntegerField(default=10, editable=False)),
                ('balance_after', models.PositiveBigIntegerField(editable=False)),
                ('source', models.CharField(choices=[('points', 'Points')], default='points', editable=False, max_length=16)),
                ('unlocked_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='section_unlocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'section'), name='section_unlock_once'), models.CheckConstraint(condition=models.Q(('section__in', ['discounts', 'rewards', 'offers', 'news', 'weather'])), name='section_unlock_valid_section'), models.CheckConstraint(condition=models.Q(('points_spent', 10), ('source', 'points')), name='section_unlock_paid_ten')],
            },
        ),
        migrations.RunPython(protect_unlocks, remove_protection),
    ]
