# Generated by Django 5.2.1 on 2026-09-25 19:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models



def protect_discount_records(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("""
            CREATE FUNCTION cp_discount_access_permanent() RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN RAISE EXCEPTION 'Purchased deal access is permanent.' USING ERRCODE = '23514'; END;
            $$;
            CREATE TRIGGER cp_discount_access_permanent BEFORE UPDATE OR DELETE
            ON customerpanel_customerdiscountaccess FOR EACH ROW EXECUTE FUNCTION cp_discount_access_permanent();
            CREATE FUNCTION cp_discount_free_publication() RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN
                IF TG_OP = 'UPDATE' AND OLD.free_published_at IS NOT NULL
                   AND NEW.free_published_at IS DISTINCT FROM OLD.free_published_at THEN
                    RAISE EXCEPTION 'Free publication history is permanent.' USING ERRCODE = '23514';
                END IF;
                IF NEW.active AND NEW.points_to_unlock_deal = 0 AND NEW.free_published_at IS NULL THEN
                    NEW.free_published_at := CURRENT_TIMESTAMP;
                END IF;
                RETURN NEW;
            END;
            $$;
            CREATE TRIGGER cp_discount_free_publication BEFORE INSERT OR UPDATE
            ON customerpanel_discount FOR EACH ROW EXECUTE FUNCTION cp_discount_free_publication();
        """)
    elif schema_editor.connection.vendor == 'sqlite':
        for action in ('UPDATE', 'DELETE'):
            schema_editor.execute(f"CREATE TRIGGER cp_discount_access_{action.lower()} BEFORE {action} ON customerpanel_customerdiscountaccess "
                "BEGIN SELECT RAISE(ABORT, 'Purchased deal access is permanent.'); END;")
        schema_editor.execute("""
            CREATE TRIGGER cp_discount_free_history BEFORE UPDATE ON customerpanel_discount
            WHEN OLD.free_published_at IS NOT NULL AND NEW.free_published_at IS NOT OLD.free_published_at
            BEGIN SELECT RAISE(ABORT, 'Free publication history is permanent.'); END;
        """)
        for action in ('INSERT', 'UPDATE'):
            schema_editor.execute(f"CREATE TRIGGER cp_discount_free_{action.lower()} AFTER {action} ON customerpanel_discount "
                "WHEN NEW.active AND NEW.points_to_unlock_deal = 0 AND NEW.free_published_at IS NULL "
                "BEGIN UPDATE customerpanel_discount SET free_published_at = CURRENT_TIMESTAMP WHERE id = NEW.id; END;")


def remove_discount_protection(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('DROP TRIGGER cp_discount_access_permanent ON customerpanel_customerdiscountaccess;')
        schema_editor.execute('DROP FUNCTION cp_discount_access_permanent();')
        schema_editor.execute('DROP TRIGGER cp_discount_free_publication ON customerpanel_discount;')
        schema_editor.execute('DROP FUNCTION cp_discount_free_publication();')
    elif schema_editor.connection.vendor == 'sqlite':
        for name in ('cp_discount_access_update', 'cp_discount_access_delete', 'cp_discount_free_history', 'cp_discount_free_insert', 'cp_discount_free_update'):
            schema_editor.execute(f'DROP TRIGGER {name};')


class Migration(migrations.Migration):

    dependencies = [
        ('customerpanel', '0009_customer_section_unlock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(blank=True, max_length=320)),
                ('details', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('food-drink', 'Food & Drink'), ('fashion', 'Fashion'), ('beauty', 'Beauty'), ('tech-gaming', 'Tech & Gaming'), ('travel', 'Travel'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('other', 'Other')], max_length=20)),
                ('deal_type', models.CharField(choices=[('percent', 'Percent off'), ('money', 'Money off'), ('fixed', 'Fixed price'), ('free', 'Free'), ('bogo', '2-for-1 / Buy one get one'), ('other', 'Special offer / Other')], default='other', max_length=12)),
                ('value_label', models.CharField(help_text='For example: 30% off, From £5, or Second main for £1.', max_length=80)),
                ('percentage_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(100)])),
                ('money_off_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='GBP', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$')])),
                ('eligibility', models.TextField(blank=True, help_text='Requirements such as student status, new customers, days or activation conditions.')),
                ('country', models.CharField(blank=True, help_text='Use a consistent country name; blank means not specified.', max_length=80)),
                ('region', models.CharField(blank=True, max_length=160)),
                ('usage_channels', models.JSONField(blank=True, default=list)),
                ('promo_code', models.CharField(blank=True, help_text='Retained server-side until this customer has free or purchased access.', max_length=160)),
                ('official_url', models.URLField(blank=True, max_length=2048, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('ongoing', models.BooleanField(default=False)),
                ('terms_summary', models.TextField(blank=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=2048, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('search_keywords', models.CharField(blank=True, max_length=500)),
                ('points_to_unlock_deal', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('free_published_at', models.DateTimeField(blank=True, editable=False, help_text='A deal published for free stays free. Create a separate deal for a paid version.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-featured', '-created_at', 'id'],
                'indexes': [models.Index(fields=['active', 'category'], name='discount_category_idx'), models.Index(fields=['active', 'valid_until'], name='discount_expiry_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('points_to_unlock_deal__gte', 0)), name='discount_nonnegative_cost'), models.CheckConstraint(condition=models.Q(('percentage_value__isnull', True), models.Q(('percentage_value__gt', 0), ('percentage_value__lte', 100)), _connector='OR'), name='discount_percent_range'), models.CheckConstraint(condition=models.Q(('money_off_value__isnull', True), ('money_off_value__gt', 0), _connector='OR'), name='discount_money_positive'), models.CheckConstraint(condition=models.Q(('valid_from__isnull', True), ('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='discount_date_order'), models.CheckConstraint(condition=models.Q(('ongoing', False), ('valid_until__isnull', True), _connector='OR'), name='discount_ongoing_no_expiry'), models.CheckConstraint(condition=models.Q(('active', False), ('ongoing', True), ('valid_until__isnull', False), _connector='OR'), name='discount_published_window'), models.CheckConstraint(condition=models.Q(('free_published_at__isnull', True), ('points_to_unlock_deal', 0), _connector='OR'), name='discount_published_free')],
            },
        ),
        migrations.CreateModel(
            name='CustomerDiscountAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_spent', models.PositiveIntegerField(editable=False)),
                ('balance_after', models.PositiveBigIntegerField(editable=False)),
                ('unlocked_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='discount_access', to=settings.AUTH_USER_MODEL)),
                ('discount', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='customer_access', to='customerpanel.discount')),
            ],
            options={
                'ordering': ['-unlocked_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'discount'), name='discount_access_once'), models.CheckConstraint(condition=models.Q(('points_spent__gt', 0)), name='discount_access_paid')],
            },
        ),
        migrations.CreateModel(
            name='DiscountVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(-1, 'Negative'), (1, 'Positive')])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='customerpanel.discount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'discount'), name='discount_vote_once'), models.CheckConstraint(condition=models.Q(('value__in', [-1, 1])), name='discount_vote_value')],
            },
        ),
        migrations.RunPython(protect_discount_records, remove_discount_protection),
    ]
